### ISSUE TITLE
Add .config to each project

### ISSUE THREAD

**Issue by oleoneto** [oleoneto/django-clite#24]
Use this file to sort of cache relevant information about each project. Mainly information generated by the CLI.

```javascript
// .cli_config.json

"project": "project_name",
"apps": [{"blog": "path/to/blog", }],
"settings": "path/to/settings",
"remotes": [{"github": "https://github.com/user/repo"}],
"build_with": "docker",
"port": 8001,
"protocol": "http",
"extra_args": []
```

or

```yaml
# .cli_config.yaml

project: 'project_name'
apps:
- blog: 'path/to/blog'
- polls: 'path/to/polls'
settings: 'path/to/settings'
remotes:
- github: 'https://github.com/user/repo'
build_with: docker
port: 8001
protocol: http
extra_args:
- ....
```
